MODEL:
    IMAGE_SIZE: [256, 256]
    HEATMAP_SIZE: [128, 128]

DATASET_COFW:
    DATASET: COFW
    TRAINSET: D:\Users\Administrator\dataset\cofw\COFW_train_color.mat
    TESTSET: D:\Users\Administrator\dataset\cofw\COFW_test_color.mat
    DATA_DIR: D:\Users\Administrator\dataset\cofw\
    FLIP: True
    SCALE_FACTOR: 0.25
    ROT_FACTOR: 30
    NUM_LANDMARKS: 29
    LANDMARK_INDEX:  [ 49, 62, 53, 58, 51, 56, 60, 64,  # brow 8 (0-7)
                    78, 96, 84, 90, 81, 87, 93, 99,  # eyes 8 (8-15)
                    122, 123, #pupil 2 (16, 17)
                    76, 77, 70, 73,  # //nose 4 (18-21)
                    102, 108, 105, 116, 120, 111,  # mouth 6 (22-27)
                    24 # chin 1  (28)
                     ]

DATASET_WFLW:
    DATASET: WFLW
    ROOT: D:\Users\Administrator\dataset\wflw\WFLW_images
    DATA_DIR: D:\Users\Administrator\dataset\wflw\
    TRAINSET: D:\Users\Administrator\dataset\wflw\face_landmarks_wflw_train.csv
    TESTSET: D:\Users\Administrator\dataset\wflw\face_landmarks_wflw_test.csv
    FLIP: True
    SCALE_FACTOR: 0.25
    ROT_FACTOR: 30
    NUM_LANDMARKS: 98
    LANDMARK_INDEX: [ 0, 2, 4, 6, 7, 9, 10, 12, 13, 14, 16, 17, 18, 20, 21, 23, 24,  # left chin (0-16) 24 chin center
                    25, 27, 28, 29, 31, 32, 34, 35, 36, 38, 39, 41, 43, 44, 46, 47,  # right chin (17-32)
                    49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,  # brow (33-50)
                    67, 68, 69, 70, 71, 72, 73, 74, 75,  # nose 9 (51-59)
                    78, 79, 81, 82, 84, 85, 87, 89, 90, 92, 93, 95, 96, 97, 99, 101,  # eyes 16 (60-75)
                    102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, # mouth 20 (76-95)
                    122, 123 # pupil 2 (96-97) background
                    ] #背景

DATASET_300W:
    DATASET: 300W
    TRAINSET: D:\Users\Administrator\dataset\300W\train.tsv
    TESTSET: D:\Users\Administrator\dataset\300W\test_ibug.tsv
    DATA_DIR: D:\Users\Administrator\dataset\300W\
    FLIP: True
    SCALE_FACTOR: 0.25
    ROT_FACTOR: 30
    NUM_LANDMARKS: 68
    LANDMARK_INDEX:   [ 1, 3, 5, 8, 11, 15, 19, 22, 24,  # left chin (0-8) 24 chin center
                         26, 30, 33, 37, 40, 42, 45, 48,  # right chin (9-16)
                         49, 50, 51, 52, 53, 58, 59, 60, 61, 62,  # brow (17-26)
                         67, 68, 69, 70, 71, 72, 73, 74, 75,   # nose 9 (27-35)
                         78, 80, 83, 84, 86, 88, 90, 91, 94, 96, 98, 100, # eyes 12 (36-47)
                         102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121 # mouth 20 (48-67)
                         ] #背景

DATASET_AFLW:
    DATASET: AFLW
    TRAINSET: D:\Users\Administrator\dataset\aflw\aflw\aflw\face_landmarks_aflw_train.csv
    TESTSET: D:\Users\Administrator\dataset\aflw\aflw\aflw\face_landmarks_aflw_test.csv
    DATA_DIR: D:\Users\Administrator\dataset\aflw\aflw\aflw\
    FLIP: True
    SCALE_FACTOR: 0.25
    ROT_FACTOR: 30
    NUM_LANDMARKS: 19
    LANDMARK_INDEX: [ 49, 51, 53, 58, 60, 62,  # brow 6 (0-5)
                    78, 122, 84, 90, 123, 96,  # eyes 6 (6-11)
                    76, 70, 77,  # nose 3 (12-14)
                    102, 120, 108,  # mouth 3 (15-17)
                    24, # chin 1 (18)
                    ] #背景

TRAIN:
    BATCH_SIZE: 2
    SHUFFLE: True
    LARGEST_NUM: 20000
TEST:
    BATCH_SIZE: 8
    SHUFFLE: True

nPoints: 124
num_iters: 100000
lr: 1.0e-4
beta1: 0.5
beta2: 0.999
weightDecay: 0
resume_iters: 0
phase: train
attr: test
gamma: 3

rotFactor: 30
res: 128

WORKERS: 8
use_tensorboard: True
best_model: checkpoint/models/best_checkpoint.pth.tar

log_dir: checkpoint/logs
model_save_dir: checkpoint/models

log_step: 500
model_save_step: 500
lr_update_step: 40000

PIN_MEMORY: True


